version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/deployment
# hooks:
#   BeforeInstall:
#     - location: deploy/scripts/before_install.sh
#       timeout: 300
#       runas: ubuntu
#   ApplicationStart:
#     - location: deploy/scripts/start_server.sh
#       timeout: 300
#       runas: ubuntu


